version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Instalando Google Chrome..."
      - curl https://intoli.com/install-google-chrome.sh | bash || echo "Fallo al instalar Chrome"
      - google-chrome --version || which google-chrome
      - chmod +x ./setup-chromedriver.sh
      - ./setup-chromedriver.sh

  pre_build:
    commands:
      - echo "Compilando el proyecto..."
      - mvn compile

  build:
    commands:
      - echo "Ejecutando pruebas..."
      - mvn test

artifacts:
  files:
    - target/surefire-reports/**